export const catagoryLists = [
  "Animation",
  "Comedy",
  "Cult/Original Trash",
  "Documentary/Mockumentary",
  "Drama",
  "Dramedy",
  "Fan Film",
  "Horror",
  "LGBT",
  "Musical/Videoclip",
  "No Fiction/Reality",
  "Romance",
  "SciFi/Fantasy Comedy",
  "SciFi/Fantasy No Comedy",
  "Sketch",
  "Social",
  "Thriller",
  "War/Action",
];
export const personalList = [
  "Youtuber Senior (maggiore di 100.000 iscritti)",
  "Youtuber Junior (minore di 100.000 iscritti)",
  "Gamer Senior (maggiore di 100.000 iscritti)",
  "Gamer Junior (minore di 100.000 iscritti)",
];
export const canaliList = [
  "Animazione",
  "Cinema, TV e Intrattenimento",
  "Cucina e Salute",
  "Giochi",
  "Informazione",
  "Mistero e Occulto",
  "Moda e Bellezza",
  "Musica",
  "LGBT",
  "Scienza, Tecnologia e Istruzione",
  "Sport",
  "Umorismo",
];
export const winner2016List = [
  { tite: "Best Creation", winners: ["AIRLOCK", "Cam Girls", "CODED"] },
  {
    tite: "Best Season",
    winners: ["La Supercafetera", " Il Camerlengo", "Shadowrunners"],
  },
  {
    tite: "Best Video/Short film/Film",
    winners: ["CLOSER", "The Crow - Shreds of Memories", "TAMA KELEN"],
  },
  {
    tite: "Best Directing",
    winners: [
      "Angelo Licata (CLOSER)",
      "Floriana Buonomo e Geraldine Ottier (LSB)",
      "Karlton T. Clay (Color Blind)",
    ],
  },
  {
    tite: "Best Screenplay",
    winners: [
      "Riccardo Sirignano (Anime e Sangue)",
      "Massimo Mento (Unico Grande Amore)",
      "Alberto Guerra (Hai visto Tom Collins?)",
    ],
  },
  {
    tite: "Best Cinematography",
    winners: ["Zyara", "Number of Silence", "Desenterrados"],
  },
  {
    tite: "Best Film Editing",
    winners: ["BIGSHOT", "Jenny & Jeff", "Illusione"],
  },
  {
    tite: "Best Actor",
    winners: [
      "Luis Molteni - Cardinal Walter (Il Camerlengo)",
      "Mark Coles Smith - Jonah Ashbrook (AIRLOCK)",
      "Ettore Nicoletti – Arthur (Arthur)",
    ],
  },
  {
    tite: "Best Actress",
    winners: [
      "Giulia Faggioni – Elisa (Sanguigna)",
      "Emanuela Pacotto - Emanuela, Mia Destiny (CENSORS)",
      "Rita Rusciano - Takiko Okuda (Fushigi Yugi Live Action)",
    ],
  },
  {
    tite: "Best Supporting Actor",
    winners: [
      "Matteo Cerullo – Kevin (CODED)",
      "Adelmo Macchioni – Mosè (Nero - La serie)",
      "Matt Danalewich - Greg (A.I. Toilet)",
    ],
  },
  {
    tite: "Best Supporting Actress",
    winners: [
      "Annie Ruby – Nikki (Cam Girls)",
      "Helene Galek - Aunt Carol (That Reminds Me...)",
      "Catia Machado – Rachel/Eve (Ma femme est pasteure)",
    ],
  },
  {
    tite: "Best Cast",
    winners: ["AIRLOCK", "Snippets Of A Lifetime", "Welcome to Italy"],
  },
  {
    tite: "Best Trailer",
    winners: ["La minute Berti", "The Crawler in the Dark", "Wonderland"],
  },
  {
    tite: "Best Scene",
    winners: [
      "Burning Wishes Ep. 04 - 04:42",
      "CLOSER – 08:05",
      "Still Time: 05:30",
    ],
  },
  { tite: "Best Poster", winners: ["Arthur", "AIRLOCK", "Nero - La serie"] },
  {
    tite: "Special Mentions",
    winners: [
      "Artistic Directors Awards: Zyara",
      "Giury Awards: Snippets Of A Lifetime",
      "Rome City Awards: Il Camerlengo",
    ],
  },
  {
    tite: "Golden Stars",
    winners: [
      "Angelo Licata",
      "Atzushi Ogata",
      "Emergingseries",
      "Universal Movies",
      "Vincenzo Alfieri",
      "Web Series Today",
    ],
  },
];

export const award2016List = [
  {
    title: "Acaro",
    awards: [
      "Best Directing Romance",
      "Andrea Mattia Grieco",
      "Best Romance Supporting Actress",
      "Valentina Loi - Mamma Nico ",
      "Best Romance Trailer",
      "Best Romance Poster",
    ],
  },
  {
    title: "A.I. Toilet",
    awards: [
      "Best SciFi/Fantasy Comedy Screenplay",
      "Vinay Murthy",
      "Best SciFi/Fantasy Comedy Cinematography",
      "Best SciFi/Fantasy Comedy Supporting Actor",
      "Greg -- Matt Danalewich",
    ],
  },
  {
    title: "AIRLOCK",
    awards: [
      "Best SciFi/Fantasy No Comedy",
      "Best SciFi/Fantasy No Comedy Film Editing",
      "Best SciFi/Fantasy No Comedy Actor",
      "Mark Coles Smith - Jonah Ashbrook",
      "Best SciFi/Fabtasy No Comedy Cast",
      "Best SciFi/Fantasy No Comedy Poster",
      "Best Sexy Actor",
      "Mark Coles Smith",
      "Best Art Directing",
      "Best Producing",
      "Universal Movies (Best Blockbuster)",
    ],
  },
  {
    title: "Alla scoperta dei 4 elementi",
    awards: [
      "Best Directing Animation",
      "Michele Pinto ",
      "Best Animation Cinematography",
      "Best Animation Supporting Characters",
      "Child voice",
    ],
  },
  {
    title: "Anime e Sangue - La Strada per Casa",
    awards: [
      "Best SciFi/Fantasy No Comedy Screenplay",
      "Riccardo Sirignano",
      "Best SciFi/Fantasy No Comedy Actress",
      "Perla Ambrosini – Pan",
      "Best SciFi/Fantasy No Comedy Trailer",
      "Best Makeup",
    ],
  },
  {
    title: "Apanyats",
    awards: [
      "Best Cult/Original Trash Film Editing",
      "Apanyats",
      "Best Cult/Original Trash Scene",
      "Apanyats Ep. 02 – 00:52",
    ],
  },
  {
    title: "Arthur",
    awards: [
      "Best Horror",
      "Best Horror Film Editing",
      "Best Horror Actor",
      "Ettore Nicoletti–Arthur",
      "Best Horror Poster",
      "Best Sound",
    ],
  },
  {
    title: "Bienvenue Chez Nous",
    awards: [
      "Best Directing Sketch",
      "Victor Costa, Valentin Waeber",
      "Best Sketch Cast",
      "Best Sketch Scene",
      "Bienvenue Chez Nous Ep. 09 – 01:30",
    ],
  },
  {
    title: "BIGSHOT",
    awards: [
      "Best Animation",
      "Best Animation Screenplay",
      "Maurice Huvelin",
      "Best Animation Film Editing",
      "Best Animation Character",
      "Best Animation Poster",
      "Emergingseries (Best European Creation)",
    ],
  },
  {
    title: "Burning Wishes",
    awards: [
      "Best Dramedy Screenplay",
      "Cian McGarrigle",
      "Best Dramedy Actor",
      "Mark Doherty- Seamus",
      "Best Dramedy Scene",
      "Burning Wishes Ep. 04 - 04:42",
    ],
  },
  {
    title: "Cam Girls",
    awards: [
      "Best Dramedy",
      "Best Dramedy Actress",
      "Kate Bond – Liv",
      "Best Dramedy Supporting Actress",
      "Annie Ruby – Nikki",
      "Best Dramedy Cast",
      "Best Sexy Actress",
      "Sarah Schreiber",
    ],
  },
  {
    title: "Carwash",
    awards: [
      "Best LGBT Cinematography",
      "Best LGBT Actor",
      "Javier Cámara Bauserman - Aquiles Franco",
      "Best LGBT Supporting Actor",
      "Oscar Martínez - Tila María Sesto",
      "Best LGBT Trailer",
    ],
  },
  {
    title: "CENSORS",
    awards: [
      "Best SciFi/Fantasy Comedy Film Editing",
      "Best SciFi/Fantasy Comedy Actress",
      "Emanuela Pacotto - Emanuela, Mia Destiny",
      "Best SciFi/Fantasy Comedy Trailer",
      "Best SciFi/Fantasy Comedy Poster",
      "Best Opening/Final",
    ],
  },
  {
    title: "Charme",
    awards: ["Best Drama Cinematography", "Best Drama Trailer"],
  },
  {
    title: "Clear The Aura (AIRLOCK videoclip)",
    awards: [
      "Best Directing Musical/Videoclip",
      "Enzo Tedeschi",
      "Best Musical/Videoclip Cinematography",
      "Best Musical/Videoclip Actor/Character",
      "Tim Hilberts",
    ],
  },
  {
    title: "CLOSER",
    awards: [
      "Best Directing No Comedy SciFi/Fantasy",
      "Angelo Licata",
      "Best SciFi/Fantasy No Comedy Cinematography",
      "Best SciFi/Fantasy No Comedy Supporting Actress",
      "Francesca Gandolfo - Li-Han",
      "Best SciFi/Fantasy No Comedy Scene",
      "CLOSER – 14:35",
      "Best War/Action Scene",
      "CLOSER – 08:05",
      "Best Antagonist",
      "Rettiloide – Fabrizio Fenner",
      "Best Original Score",
      "Best Visual Effects",
    ],
  },
  {
    title: "CODED",
    awards: [
      "Best Drama",
      "Best Directing Drama",
      "Gary Harvey, Nigel Edwards",
      "Best Drama Supporting Actor",
      "Matteo Cerullo – Kevin",
      "Best Drama Supporting Actress",
      "Angela Moore - Principal Sarah",
      "Best Drama Cast",
      "Best Drama Poster",
      "Best Episode",
      "CODED Ep. 06",
    ],
  },
  {
    title: "Color Blind",
    awards: [
      "Best Directing War/Action",
      "Karlton T. Clay",
      "Best War/Action Actor",
      "Saint Abia Williams",
      "Trey Williams",
      "Best War/Action Trailer",
      "Best Villain",
      'Kelvin Rowe - Corey "Cobalt" Williams',
    ],
  },
  {
    title: "Desenterrados",
    awards: [
      "Best Horror Cinematography",
      "Best Horror Supporting Actor",
      "Juanima Mallen – Albert",
      "Best Horror Supporting Actress",
      "Maria Minaya – Nicole",
    ],
  },
  {
    title: "Ergo Sum",
    awards: [
      "Best SciFi/Fantasy No Comedy Supporting Actor",
      "Nicola Guarino – Kubrik",
      "Best Creative Idea",
    ],
  },
  {
    title: "Face to Faith",
    awards: [
      "Best No Fiction/Reality Cinematography",
      "Best No Fiction/Reality Cast/Character",
      "Best No Fiction/Reality Trailer",
    ],
  },
  {
    title: "Fushigi Yugi Live Action",
    awards: [
      "Best Fan Film Screenplay",
      "Carlo Trevisan",
      "Best Fan Film Film Editing",
      "Best Fan Film Actress",
      "Rita Rusciano - Takiko Okuda",
      "Best Fan Film Poster",
      "Best Kiss",
      "Fushigi Yugi Live Action 10:40",
    ],
  },
  {
    title: "Hai visto Tom Collins?",
    awards: [
      "Best Documentary/Mockumentary Screenplay",
      "Alberto Guerra",
      "Best Documentary/Mockumentary Actor/Character",
      "Alberto Guerra – Narratore",
      "Best Documentary/Mockumentary Supporting Actor/Character",
      "Ampello Zecchini – Barman Ep 03&04",
      "Best Documentary/Mockumentary Poster",
    ],
  },
  {
    title: "Il Camerlengo",
    awards: [
      "Best Comedy",
      "Best Directing Comedy",
      "Marco Castaldi",
      "Best Comedy Actor",
      "Luis Molteni - Cardinal Walter",
      "Best Comedy Scene",
      "Il Camerlengo Ep. 02 – 02:20",
    ],
  },
  {
    title: "Il mondo magico",
    awards: [
      "Best Directing Dramedy",
      "Raffaele Schettino",
      "Best Dramedy Supporting Actor",
      "Gaetano Tavarone – Gianni Father",
    ],
  },
  {
    title: "Illusione",
    awards: [
      "Best Social Film Editing",
      "Best Social Supporting Actor",
      "Giovanni Ferrante – Traitor",
      "Best Story",
    ],
  },
  {
    title: "ITALICUS",
    awards: [
      "Best Cult/Original Trash Screenplay",
      "Francesco Cipriani",
      "Best Cult/Original Trash Supporting Actress",
      "Raffaella Martorelli - Susy Di Menna",
    ],
  },
  {
    title: "Italy in the World",
    awards: ["Best No Fiction/Reality Screenplay", "Giuseppe Cossentino"],
  },
  {
    title: "Jenny & Jeff",
    awards: [
      "Best Romance",
      "Best Romance Film Editing",
      "Best Romance Actor",
      "Evan Martin - Jeff",
      "Best Romantic Scene",
      "Jenny & Jeff Ep. 03 – 06:35",
    ],
  },
  {
    title: "La Linea dei Topi",
    awards: [
      "Best Drama Film Editing",
      "Best Drama Actor",
      "Andrea Galatà – Marco",
      "Best Drama Actress",
      "Chiara De Caroli – Francesca",
    ],
  },
  {
    title: "La minute Berti",
    awards: [
      "Best Sketch",
      "Best Sketch Cinematography",
      "Best Sketch Supporting Actor",
      "Thomas Diebold - Papa Noël",
      "Best Sketch Supporting Actress",
      "Lorianne Cherpillod - Friend",
      "Best Sketch Trailer",
    ],
  },
  {
    title: "La Rana delle Favole",
    awards: [
      "Best Romance Cinematography",
      "Best Romance Actress",
      "Chiara Paterno- Margherita",
      "Best Romance Cast",
    ],
  },
  {
    title: "La Supercafetera",
    awards: [
      "Best SciFi/Fantasy Comedy",
      "Best Directing Comedy SciFi/Fantasy",
      "Carlos P. Brioso & Jacobo Saro",
      "Best SciFi/Fantasy Comedy Actor",
      "Nacho Ortega – Pedro",
      "Best SciFi/Fantasy Comedy Supporting Actress",
      "Elena Guevara – Carlota",
      "Best SciFi/Fantasy Comedy Cast",
      "Best SciFi/Fantasy Comedy Scene",
      "La Supercafetera: Ep 02 – 03:24",
      "YoutubeMagazineItalia (Best Web Response)",
    ],
  },
  {
    title: "Late Bloomer",
    awards: [
      "Best No Fiction/Reality Film Editing",
      "Best No Fiction/Reality Actress/Character",
      "Kaye Kittrell",
    ],
  },
  {
    title: "Lovers Lane",
    awards: [
      "Best Romance Screenplay",
      "Karlton T. Clay",
      "Best Romance Supporting Actor",
      "Ernest Jam - Minister Julio Rodriquez",
    ],
  },
  {
    title: "LSB",
    awards: [
      "Best LGBT",
      "Best Directing LGBT",
      "Floriana Buonomo e Geraldine Ottier",
      "Best LGBT Actress",
      "Denise Sicignano – Filomena",
      "Best LGBT Cast",
      "Best LGBT Scene",
      "LSB Ep. 02 – 02:53",
      "Best Female Cast",
    ],
  },
  {
    title: "Ma femme est pasteure",
    awards: [
      "Best Comedy Film Editing",
      "Best Comedy Supporting Actress",
      "Catia Machado – Rachel/Eve",
      "Best Duo of Actors",
      "Victor Costa - Carolina Costa",
    ],
  },
  {
    title: "MilzaMan",
    awards: [
      "Best Cult/Original Trash",
      "Best Directing Cult/Original Trash",
      "Antonio Vezzari, Nino Pescecane",
      "Best Cult/Original Trash Cinematography",
      "Best Cult/Original Trash Actor",
      "Lucio Ciampallari - Tony Scalici",
      "Best Cult/Original Trash Supporting Actor",
      "Mimmo Gagliano – Vecchio Pazzo",
    ],
  },
  {
    title: "Nero – La serie",
    awards: [
      "Best Directing Thriller",
      "Giuseppe Piva",
      "Best Thriller Supporting Actor",
      "Adelmo Macchioni – Mosè",
      "Best Thriller Supporting Actress",
      "Laura Locatelli – Elsa",
      "Best Thriller Cast",
      "Best Thriller Poster",
      "Best Original Song - Nero",
      "Non Solo Gor3 (Best Gore Creation)",
    ],
  },
  {
    title: "Nero – Videoclip",
    awards: ["Best Musical/Videoclip Film Editing"],
  },
  {
    title: "Night after night",
    awards: [
      "Best Drama Screenplay",
      "Federico Ciceroni",
      "Best Dramatic Scene",
      "Night after night Ep. 6 – 03:56",
      "Web Series Tv (Best Italian Creation)",
    ],
  },
  {
    title: "Number of Silence",
    awards: [
      "Best Thriller Cinematography",
      "Best Thriller Film Editing",
      "Best Thriller Actress",
      "Magdalena Kaim - Nina Novak",
      "Best Thriller Scene",
      "Number of Silence Ep. 03 – 00:08",
      "Best Pilot",
    ],
  },
  {
    title: "Passioni Senza fine",
    awards: ["Best Web Soap"],
  },
  {
    title: "Povere ma belle",
    awards: [
      "Best Cult/Original Trash Actress",
      "Chiara Serini – Kija",
      "Best Cult/Original Trash Trailer",
      "Best Cult/Original Trash Poster",
    ],
  },
  {
    title: "Rubia en apuros",
    awards: [
      "Best Sketch Screenplay",
      "Cristina G. Abril",
      "Best Sketch Actress",
      "Cristina G. Abril - Rubia",
      "Best Sketch Poster",
    ],
  },
  {
    title: "Saint Seiya - New Confessions",
    awards: [
      "Best Fan Film Cinematography",
      "Best Fan Film Supporting Actress",
      "Jun Ichikawa - Shunrei",
      "Best Fan Film Scene - Saint Seiya",
      "New Confessions Ep. 02 - 03:05",
    ],
  },
  {
    title: "Sanguigna",
    awards: [
      "Best Horror Screenplay",
      "Angelo Di Benedetto, Andrea Marchetti, Laura Di Terlizzi",
      "Best Horror Actress",
      "Giulia Faggioni – Elisa",
      "Best Horror Cast",
      "Best Horror Scene",
      "Sanguigna: Ep. 10 – 03:40",
      "Best Cliffhanger Scenes",
    ],
  },
  {
    title: "Shadowrunners",
    awards: [
      "Best War/Action",
      "Best War/Action Cinematography",
      "Best War/Action Supporting Actor",
      "Fabri - Luca Pach",
      "Best War/Action Supporting Actress",
      "Ombretta - Alessia Candido",
      "Best War/Action Cast",
      "Best Male Cast",
    ],
  },
  {
    title: "Snippets Of A Lifetime",
    awards: [
      "Best Documentary/Mockumentary",
      "Best Documentary/Mockumentary Film Editing",
      "Best Documentary/Mockumentary Actress/Character",
      "Malia",
      "Best Documentary/Mockumentary Cast/Character",
      "Best Documentary/Mockumentary Trailer",
    ],
  },
  {
    title: "Stay At Home Mom",
    awards: ["Best Dramedy Film Editing", "Best Dramedy Trailer"],
  },
  {
    title: "Still Time",
    awards: [
      "Best Social Screenplay",
      "Alessandro Orefice",
      "Best Social Scene",
      "Still Time: 05:30",
      "Best Young Actor",
      "Davide Genasi – Chris",
    ],
  },
  {
    title: "Talent Freaks",
    awards: [
      "Best No Fiction/Reality",
      "Best Directing No Fiction/Reality",
      "Andy Coon",
      "Best No Fiction/Reality Actor/Character",
      "Nathan Durfee",
      "Best No Fiction/Reality Poster",
      "WAU (Best Innovative Creation)",
    ],
  },
  {
    title: "TAMA KELEN",
    awards: [
      "Best Directing Social",
      "Michele Pinto",
      "Best Social Cinematography",
      "Best Social Supporting Actress",
      "Ludovica Filanino – Young Ibrahim lover",
      "Best Social Trailer",
      "Best Social Poster",
    ],
  },
  {
    title: "That Reminds Me...",
    awards: [
      "Best LGBT Screenplay",
      "Marla Pachter",
      "Best LGBT Film Editing",
      "Best LGBT Supporting Actress",
      "Helene Galek - Aunt Carol",
      "Best LGBT Poster",
    ],
  },
  {
    title: "The Crawler in the Dark",
    awards: [
      "Best Directing Horror",
      "JR Lipartito",
      "Best Horror Trailer",
      "Best Special Character",
      "The Crawler",
    ],
  },
  {
    title: "The Crow - Shreds of Memories",
    awards: [
      "Best Fan Film",
      "Best Directing Fan Film",
      "Pietro Cinieri",
      "Best Fan Film Actor",
      "Daniele Cervellera - Eric Crowen/Il Corvo",
      "Best Fan Film Supporting Actor",
      "Mirko D'Antona - Top Dollar",
      "Best Fan Film Cast",
      "Best Fan Film Trailer",
    ],
  },
  {
    title: "The Pantsless Detective",
    awards: [
      "Best Comedy Cinematography",
      "Best Comedy Supporting Actor",
      "Craig Kanne - New Thug",
    ],
  },
  {
    title: "They Call Me Superseven",
    awards: [
      "Best War/Action Screenplay",
      "Scott Rhodes & Jerry Kokich",
      "Best War Action Film Editing",
      "Best War/Action Actress",
      "Olivia Dunkley - Sandra West",
      "Best War/Action Poster",
    ],
  },
  {
    title: "Tutta la vita davanti agli occhi",
    awards: [
      "Best Musical/Videoclip Screenplay",
      "Angela Berlino, Anstemi",
      "Best Musical/Videoclip Actress/Character",
      "Angela Berlino",
      "Best Musical/Videoclip Poster",
      "Best Costume Design",
    ],
  },
  {
    title: "Unico Grande Amore",
    awards: [
      "Best Comedy Screenplay",
      "Massimo Mento",
      "Best Comedy Actress",
      "Francesca Verzini - Suor Serena",
      "Best Comedy Trailer",
    ],
  },
  {
    title: "Welcome to Italy",
    awards: [
      "Best Social",
      "Best Social Actor",
      "Amin Nour - Jamal",
      "Best Social Actress",
      "Irma Carolina Di Monte - Milagros",
      "Best Social Cast",
    ],
  },
  {
    title: "While Waiting for Godot",
    awards: [
      "Best Dramedy Cinematography",
      "Best Dramedy Poster",
      "Visionary Web (Best Visionary Creation)",
    ],
  },
  {
    title: "Wilson Saloon",
    awards: [
      "Best Musical/Videoclip",
      "Best Musical/Videoclip Supporting Actor/Character",
      "Nelson Burgoz - Seu Jorge/Conditioning Technician 1",
      "Best Musical/Videoclip Cast/Character",
    ],
  },
  {
    title: "Wonderland",
    awards: [
      "Best Thriller",
      "Best Thriller Screenplay",
      "Giovanni Minardi",
      "Best Thriller Actor",
      "Jacopo Marchisio - Daniele Morabito",
      "Best Thriller Supporting Actress",
      "Angelica Giusto – Francesca",
      "Best Thriller Trailer",
    ],
  },
  {
    title: "You Me We",
    awards: ["Best Comedy Cast", "Best Comedy Poster"],
  },
  {
    title: "Yukata Cowboy",
    awards: [
      "Best Sketch Film Editing",
      "Best Sketch Actor",
      "Atsushi Ogata - Yukata Cowboy",
    ],
  },
  {
    title: "Zyara",
    awards: [
      "Best Directing Documentary/Mockumentary",
      "Muriel Aboulrouss",
      "Best Documentary/Mockumentary Cinematography",
      "Best Dialogues",
      "World Wide Webserie (Best World Creation)",
    ],
  },
];

export const catagoryBaseList = [
  "Animation",
  "Comedy",
  "Cult/Original Trash",
  "Drama",
  "Dramedy",
  "Fan Film",
  "Horror",
  "LGBT",
  "Musical/Videoclip",
  "No Fiction/Documentary/Mockumentary/Reality",
  "Romance",
  "SciFi/Fantasy Comedy",
  "SciFi/Fantasy No Comedy",
  "Sketch",
  "Social",
  "Thriller",
  "War/Action",
];

export const awardSelectionList = [
  "Acaro: ITA Season 1",
  "A.I. Toilet: JAP",
  "AIRLOCK: AUS - Season 1",
  "Alla scoperta dei 4 elementi: ITA",
  "Anime e Sangue - La Strada per Casa: ITA – Season 1",
  "Apanyats: ESP – Season 1",
  "Arthur: CH – Season 1",
  "Assunta & Gennarino: ITA – Season 1",
  "Bienvenue Chez Nous: CH – Season 1",
  "BIGSHOT: FRA – Season 1",
  "Burning Wishes: IRL 1",
  "Cam Girls: USA - Season 1",
  "Carwash: MEX – Season 1",
  "CENSORS: ITA – Season 1",
  "Charme: ITA - Season 1",
  "Clear The Aura: AUS",
  "CLOSER: ITA",
  "CODED: CAN – Season 1",
  "Color Blind: USA – Season 1",
  "Dancing Dream: ITA – Season 1",
  "Desenterrados: ESP – Season 1",
  "Doppiamente: ITA - Season 1",
  "Ergo Sum: ITA – Season 1",
  "Face to Faith: CH – Season 1",
  "Father, vendetta sanguinaria: ITA Season 1",
  "Fushigi Yugi Live Action: ITA",
  "Hai visto Tom Collins? : ITA – Season 1",
  "Hig Road: NZ – Season 1",
  "Il Camerlengo: ITA – Season 1",
  "Il mondo magico: ITA",
  "Illusione: ITA",
  "ITALICUS: ITA – Season 1",
  "Italy in the World: ITA – Season 1",
  "Jenny & Jeff: CAN/ENG – Season 1",
  "La Linea dei Topi: ITA – Season 2",
  "La minute Berti: CH – Season 1",
  "La Rana delle Favole: ITA – Season 1",
  "La Supercafetera : ESP – Season 6",
  "Late Bloomer: USA – Season 4",
  "Lovers Lane: USA – Season 1",
  "LSB: ITA – Season 2",
  "Ma femme est pasteure: CH – Season 1",
  "MilzaMan: ITA – Season 1",
  "Nero – La serie: ITA - Season 1",
  "Nero – Videoclip",
  "Night after night: ITA – Season 1",
  "Number of Silence: GER – Season 1",
  "Passioni Senza fine : ITA – Season 3",
  "Povere ma belle: ITA Season 1",
  "REW La rete invisibile: ITA – Season 1",
  "Rubia en apuros: ESP – Season 1",
  "Saint Seiya - New Confessions: ITA – Season 1",
  "Sanguigna: ITA – Season 1",
  "Shadowrunners: ITA – Season 1",
  "Snippets Of A Lifetime: GER – Season 1",
  "Stay At Home Mom: USA – Season 1",
  "Still Time: ITA",
  "Super Masuyo: ITA",
  "Talent Freaks: USA – Season 2",
  "TAMA KELEN: ITA",
  "That Reminds Me... : ITA Season 1",
  "The Crawler in the Dark: JAP – Season 1",
  "The Crow - Shreds of Memories: ITA",
  "The Pantsless Detective: USA – Season 3",
  "They Call Me Superseven: USA",
  "Tutta la vita davanti agli occhi: ITA",
  "Unico Grande Amore: ITA – Season 1",
  "Welcome to Italy: ITA – Season 1",
  "While Waiting for Godot: USA – Season 2",
  "Wilson Saloon: BRA – Season 1",
  "Wonderland: ITA – Season 3",
  "You Me We: GER – Season 1",
  "Yukata Cowboy: JPN – Season 1",
  "Zyara: RL – Season 1",
];

export const excellenceAwardList = [
  ["GABRIEL: FRA – Season 1", "Best Creation"],
  ["Gifted Corporation: SPA – Season 1", "Best Season"],
  ["MEMORIES: ITA", "Best Video/Short film/Film"],
  ["MEMORIES: ITA", "Best Directing: Vincenzo Alfieri"],
  [
    "La Supercafetera: SPA – Season 5",
    "Best Screenplay: Carlos P. Brioso/Jacobo Saro",
  ],
  ["Notte Noir: SVI – Season 1", "Best Cinematography"],
  ["F*ck The Zombies: ITA – Season 1", "Best Film Editing"],
  ["Crew: USA – Season 3", "Best Actor: Nicky Greco - Skip Johnson"],
  [
    "Whatever, Linda: CAN – Season 1",
    "Best Actress: Hannah Cheesman - Linda Thoroughbred",
  ],
  [
    "You Can't Take It With You: ITA - Season 1",
    "Best Supporting Actor: Angelo Iapichino - Valerio",
  ],
  [
    "Noirhouse: AUS – Season 2",
    "Best Supporting Actress: Sara Cooper – Evangeline Kensington",
  ],
  ["De Pontis: SPA – Season 1", "Best Cast"],
  ["SanFranLand: USA – Season 1", "Best Trailer"],
  ["BISHONNEN: ITA – Season 2", "Best Scene: Ep. 10 - 00:55/04:05"],
];
